### ISSUE TITLE
Improve Reporting with Flexible Format and Output Options

### ISSUE THREAD

**Issue by azjezz** [carthage-software/mago#1]
Currently, Fennec’s reporting relies on `codespan_reporting`.

To make reporting more useful, we should create an abstraction that will support multiple output formats, such as JSON, GitHub Actions, GitLab, and others, and allow for customization within each format.

Each format will be customizable, for example, `codespan` will offer options to enable or disable color output, which is currently set to auto.

Our goal is for the new reporter to operate using two main components: a `formatter`, responsible for formatting the content, and a `writer`, which directs the output to a specified destination.

The destination should be configurable to options like `stdout`, `stderr`, or a file path.

**Comment by kczx3** [comment]
Is GitLab's (CodeClimate) report format supported with the commit that is indicated as closing this?  I can't immediately tell.

**Comment by azjezz** [comment]
Yes, we support gitlab format now. You can see supported formats by running `mago lint --reporting-format=`

We should probably update the documentation to show this there.
