### ISSUE TITLE
bug(formatter): out of bound char access

### ISSUE THREAD

**Issue by FutsalShuffle** [carthage-software/mago#16]
php version: 8.1
platform: arm64/darwin (m3 pro with 11 cores)

terminal output:

`⠠ 🖊️  Writing     ▕▇                                                                                                      ▏     3/315▕    1%▕  ETA: 00:00:00▕  Elapsed: 00:00:00thread 'tokio-runtime-worker' panicked at crates/formatter/src/lib.rs:217:29:
byte index 443 is not a char boundary; it is inside 'о' (bytes 442..444) of `<?php

namespace App\Models;

use Illuminate\Support\Collection;

class Stage extends BaseEnumModel
{
    public const NEW = 1;
    public const WORK = 2;
    public const DONE = 3;
    public const REVIEW = 4;
    public const READY_TO_TEST = 5;
    publi`[...]
stack backtrace:
   0:        0x1028ba624 - __mh_execute_header
   1:        0x102438f88 - __mh_execute_header
   2:        0x1028966dc - __mh_execute_header
   3:        0x1028bdbb4 - __mh_execute_header
   4:        0x1028bda30 - __mh_execute_header
   5:        0x1028be238 - __mh_execute_header
   6:        0x1028bdc7c - __mh_execute_header
   7:        0x1028bdbec - __mh_execute_header
   8:        0x1028bdbe0 - __mh_execute_header
   9:        0x102904468 - __mh_execute_header
  10:        0x10243e4ac - __mh_execute_header
  11:        0x102904900 - __mh_execute_header
  12:        0x1024f5f24 - __mh_execute_header
  13:        0x1024fd174 - __mh_execute_header
  14:        0x10250b0d4 - __mh_execute_header
  15:        0x1024fb050 - __mh_execute_header
  16:        0x1024f6d50 - __mh_execute_header
  17:        0x1024fa9dc - __mh_execute_header
  18:        0x1024f6d50 - __mh_execute_header
  19:        0x1024b8b68 - __mh_execute_header
  20:        0x1024b7398 - __mh_execute_header
  21:        0x1028c4e7c - __mh_execute_header
  22:        0x1028ca3a4 - __mh_execute_header
  23:        0x1028c67cc - __mh_execute_header
  24:        0x1028c6444 - __mh_execute_header
  25:        0x1028bedac - __mh_execute_header
  26:        0x18677a034 - __pthread_joiner_wake
zsh: abort      RUST_BACKTRACE=full mago format
`

![image](https://github.com/user-attachments/assets/9a56df06-38ee-444e-8c20-8fbe72ad9b04)
it also appeared to have fully erase entire files (image example). its not the only file like this. and it doesn't happen to same file twice on checkout and rerun. maybe some concurrency issue?

**Comment by FutsalShuffle** [comment]
small update: after multiple reruns with setting thread amount to 1 in config i wasn't able to reproduce second issue. my guess would be a concurrency issue when writing a lot of files with many threads (maybe macos specific).

**Comment by azjezz** [comment]
Hi, thank you for reporting this.

It is definitly not a concurrency issue, as the error is coming from reading into an invalid byte of the code, and we only read the code from the disk once.

I will try to reproduce this, but if you could please share the file that caused this, it would be really helpful.


This is also not something to do with MacOS, as i am also using an M1 for development, and i have also run multiple tests on my M3 with no issues.

**Comment by azjezz** [comment]
are you using unicode characters in your code by any chance?

**Comment by azjezz** [comment]
fixed. please let me know if this issue comes up again :)

**Comment by azjezz** [comment]
fix has been released in 0.0.6.

**Comment by FutsalShuffle** [comment]
indeed the issue seems to be fixed, thank you!
