### ISSUE TITLE
`fmt` producing bad code - new without parentheses

### ISSUE THREAD

**Issue by bendavies** [carthage-software/mago#20]
hi

in my `composer.json` I have

`"php": "^8.3",`

`fmt` on is formatting code valid for
https://wiki.php.net/rfc/new_without_parentheses
which is only valid for 8.4

It shouldn't do this, right?

**Comment by nhedger** [comment]
You may be correct, but I think including a minimal reproduction snippet would help.

**Comment by azjezz** [comment]
can you please share a code example that results in PHP 8.4 only syntax? i tried couple of options but i couldn't get it to output new without parens.

ref: https://github.com/carthage-software/mago/blob/6177bc12841624dc2aef8383b6ea2df6e915cdbf/crates/formatter/src/parens.rs#L175-L190

**Comment by bendavies** [comment]
https://github.com/brick/date-time/blob/db33701540dd80d8c55d529d697582688f9e4cbb/src/Parser/IsoParsers.php#L41


```sh
git clone git@github.com:brick/date-time.git
cd date-time
cp ~/Downloads/mago-0.0.6-aarch64-apple-darwin/mago .
curl https://raw.githubusercontent.com/carthage-software/mago/refs/heads/main/examples/mago-full.toml -o mago.toml
chmod +x mago
xattr -rd com.apple.quarantine mago
./mago fmt
git diff src/Parser/IsoParsers.php
```

**Comment by bendavies** [comment]
there some other interesting diffs here...
different issue but this doesn't look equivalent. or is it?
<img width="629" alt="image" src="https://github.com/user-attachments/assets/cd4b9fa2-ec15-46d5-9edd-6f3e159797cd">

**Comment by jdreesen** [comment]
I think it is equivalent, because the operator precedence of `&&` is higher than `||`. 

But I think the parenthesis should stay, as it could be confusing otherwise.

**Comment by bendavies** [comment]
indeed, confirmed equivalent with the test suite and modifying it further.
but yes, hard to grok without the parens.

**Comment by azjezz** [comment]
@bendavies the reason that paren is removed is that we actually remove all parens from around expressions, and put them back only when needed.

we can add a setting to add parens in that case.

ref: https://github.com/carthage-software/mago/blob/6177bc12841624dc2aef8383b6ea2df6e915cdbf/crates/formatter/src/parens.rs#L19

**Comment by bendavies** [comment]
No problem, it's not a bug. Can raise another issue. I hope my reproducer on the original issue was good for you.

**Comment by azjezz** [comment]
fixed.
