### ISSUE TITLE
Feature request: report as checkstyle format

### ISSUE THREAD

**Issue by M-arcus** [carthage-software/mago#22]
In GitHub actions lint results can be report via checkstyle format which will automatically show up in the file diffs: https://github.com/staabm/annotate-pull-request-from-checkstyle

**Comment by nhedger** [comment]
Wouldn't it be more appropriate to directly report errors and warnings using GitHub Actions native error reporting mechanism?

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-error-message

These already create annotations

**Comment by M-arcus** [comment]
@nhedger
is this already part of https://github.com/carthage-software/mago? 
if not, I will adjust the title
if yes, I'll close this issue

**Comment by azjezz** [comment]
I agree, we should definitly support more formats in the reporter, but to me, this is not a priority as much as getting the functionality out, but will keep this issue open for future reference.

**Comment by azjezz** [comment]
I just added support for multiple report formats in [this commit](https://github.com/carthage-software/mago/commit/60ba66de9e16b9ca320c2fac5780e6a5cb23ba5c), but the `checkstyle` format hasn't been implemented yet.

If you'd like to contribute, this would be a great opportunity to help! 

To get started, you'll need to:
1. Add `Checkstyle` to the `ReportingFormat` enum: https://github.com/carthage-software/mago/blob/60ba66de9e16b9ca320c2fac5780e6a5cb23ba5c/crates/reporting/src/reporter.rs#L34
2. Implement an emitter for it, see: https://github.com/carthage-software/mago/blob/60ba66de9e16b9ca320c2fac5780e6a5cb23ba5c/crates/reporting/src/internal/emitter/mod.rs#L45-L61

I'll try to work on this later today or tomorrow if no one picks it up by then.

**Comment by azjezz** [comment]
checkstyle format has been implemented in 0.0.10.

https://github.com/carthage-software/mago/releases/tag/0.0.10

**Comment by M-arcus** [comment]
@azjezz Thank you! :rocket:
