### ISSUE TITLE
`lint` panics on empty multiline comment with no content `/**/`

### ISSUE THREAD

**Issue by vvvinceocam** [carthage-software/mago#27]
Hello,

The `lint` subcommand panics when it parse a multiline comment with no content `/**/`. The 2 consecutive stars cause the comment to be treated as a docblock.

Reproduction sample:

```php
<?php

/**/
```

Error:

```
thread 'tokio-runtime-worker' panicked at crates/linter/src/plugin/comment/rules/utils.rs:18:35:
begin <= end (3 <= 2) when slicing `/**/`
```

Thank you !

**Comment by azjezz** [comment]
Nice catch!

Will be fixed!

**Comment by azjezz** [comment]
fixed in https://github.com/carthage-software/mago/commit/5c6c9994996859974ae8caa88bd3c28504fe903a

**Comment by azjezz** [comment]
this also inspired a new linter rule :) https://github.com/carthage-software/mago/commit/dd8ce40834adec7d5fb8ca611ed42fc873e57613

**Comment by azjezz** [comment]
fixed as of https://github.com/carthage-software/mago/releases/tag/0.0.10
