### ISSUE TITLE
Using Mago as an Syntax Linter

### ISSUE THREAD

**Issue by shyim** [carthage-software/mago#31]
We check automated for Syntax Errors in our code base by using `php -l` with the right php version and when the dev uses newer language constructs it fails.

Do you think this could be done in mago? Setting the php version in the config and any new language features will be shown as error 🤔

**Comment by azjezz** [comment]
Hi! yes, actually we already do this prior to linting via the semantics crate, we can expose this functionally in the command line to show only semantics issues.

**Comment by azjezz** [comment]
implemented in https://github.com/carthage-software/mago/commit/700a56a490c596b6b030adfe7461c01f89755131 as `mago check`.
