### ISSUE TITLE
Key documentation missing: config paths

### ISSUE THREAD

**Issue by SMcCandlish** [carthage-software/mago#34]
From `mago --help`:

`lint         Lint the project according to the `mago.toml` configuration or default settings`
`format       Format source files using defined rules.`

There's no indication (including via `mago help lint` and `mago help format`) where mago is going to look for a configuration file and a format-rules definition file, or what these files should be named. One is tempted to assume that default ones would go somewhere under `/etc/` and that overrides could be passed for a specific task via the `mago` command line, and/or placed in the directory in which mago is operating; but who knows? If I had all day to peruse the source code of this, I could probably figure it out, but I'm trying to use mago to work on my own complex and overdue projects, not trying to join the mago documentation team.  ;-)

**Comment by azjezz** [comment]
Thanks for the feedback.

The configuration file (mago.toml) and examples are described in the README here: https://github.com/carthage-software/mago?tab=readme-ov-file#usage

We're aware that our documentation needs improvement, but we're still in early stages of development. Contributions are welcome - feel free to submit a PR if you have time.

**Comment by SMcCandlish** [comment]
I read the readme, of course, and that section mentions a sample configuration file, but it doesn't say anything about where it is expected to live in the Linux (or macOS or whatever) filesystem. Some users are going to be installing this via a package manager, too (that's how I got it originally) which just provides the binary executable, not any documentation, examples, etc.  So having "how to set up and use this" information is going to be important. Is the app going to be looking for a default `/etc/mago/mago.toml`? Is a `mago.toml` required in the directory of where the code is that you want to run through `mago`? Is it optionally put there, just to override defaults that are hard-coded? Where does a format-rules definition file go? What belongs in it? What happens if there isn't one? Is there an `/etc/mago/[something].toml` that sets defaults? The basics, basically.

**Comment by azjezz** [comment]
we now have documentation, see:

- https://mago.carthage.software/#/getting-started/
- https://mago.carthage.software/#/getting-started/configuration

**Comment by SMcCandlish** [comment]
Woot!
